name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://nelarius/imnodes-docker-builder:latest
    steps:
      # This step uses checkout action: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
      - name: premake5
        run: premake5 gmake --sdl-include-path=/usr/include/SDL2
      - name: make-debug
        run: make all config=debug -j
      - name: make-release
        run: make all config=release -j
      # - name: meson # needs meson and ninja
      #   run: meson build
      # - name: mesoncompile
      #   run: meson compile -C build
